# Generated by Django 2.1.1 on 2019-12-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availale_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
